kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume-connection
  labels:
    type: local
    app: postgres-connection
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-connection
  labels:
    app: postgres-connection
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-connection
  labels:
    app: postgres-connection
spec:
  type: NodePort
  selector:
    app: postgres-connection
  ports:
   - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-connection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-connection
  template:
    metadata:
      labels:
        app: postgres-connection
    spec:
      containers:
        - name: postgres
          image: postgis/postgis:12-2.5-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: db-env-connection
                key: DB_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: db-env-connection
                key: DB_NAME
          volumeMounts:
            - mountPath: /var/lib/postgresql/data-2
              name: postgresdb
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pv-claim-connection
